baseURL = 'https://kanvas.meshery.io' #temporary
title = 'Kanvas'
canonifyurls = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Getting Started"
    url = "/getting-started/"
    weight = 20

  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 30

[params]
  dark-mode = true
  logo_light = "images/kanvas-logo-light.svg"
  logo_dark = "images/kanvas-logo-dark.svg"
  description = "Collaborative cloud native management for Kubernetes"
